# 1)  Hierarchical Indexing 

Hierarchical indexing is an important feature of pandas that enables you to have mul‐
tiple (two or more) index levels on an axis

In [2]:
import pandas as pd
import numpy as np


In [3]:
data=pd.DataFrame(np.random.randn(9),index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],[1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

0
a 1 -0.509921
  2  0.300815
  3  0.084153
b 1 -0.492126
  3 -0.278273
c 1 -0.046700
  2 -0.742645
d 2  0.684257
  3 -0.859794

In [4]:
data['b':'c']

0
b 1 -0.492126
  3 -0.278273
c 1 -0.046700
  2 -0.742645

In [5]:
data.unstack()

0                    
          1         2         3
a -0.509921  0.300815  0.084153
b -0.492126       NaN -0.278273
c -0.046700 -0.742645       NaN
d       NaN  0.684257 -0.859794

In [6]:
data.loc[:]

0
a 1 -0.509921
  2  0.300815
  3  0.084153
b 1 -0.492126
  3 -0.278273
c 1 -0.046700
  2 -0.742645
d 2  0.684257
  3 -0.859794

In [8]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],
                   columns=[['ohio','ohio','virginia'],['green','green','red']])

In [9]:
frame

ohio       virginia
    green green      red
a 1     0     1        2
  2     3     4        5
b 1     6     7        8
  2     9    10       11

In [10]:
frame.index.names=['key1','key2']
frame.columns.names=['state','color']

In [11]:
frame

state      ohio       virginia
color     green green      red
key1 key2                     
a    1        0     1        2
     2        3     4        5
b    1        6     7        8
     2        9    10       11

In [12]:
frame['ohio']

color      green  green
key1 key2              
a    1         0      1
     2         3      4
b    1         6      7
     2         9     10

In [16]:

frame.sum(level='color',axis=1)

color      green  red
key1 key2            
a    1         1    2
     2         7    5
b    1        13    8
     2        19   11

In [17]:

frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1), 'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'], 'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [19]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

# 2) Combining and Merging 

In [21]:
df1=pd.DataFrame({'key1':['b', 'b', 'a', 'c',],'data1':range(4)})
df2=pd.DataFrame({'key1':['a','b','d'],'data2':range(3)})

df1

key1  data1
0    b      0
1    b      1
2    a      2
3    c      3

In [22]:
df2

key1  data2
0    a      0
1    b      1
2    d      2

In [23]:
pd.merge(df1,df2,on='key1',how='inner') #Here the 'ON' argument acts as a base column or base index

key1  data1  data2
0    b      0      1
1    b      1      1
2    a      2      0

In [24]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df4 = pd.DataFrame({'lkey': ['a', 'b', 'd'],'data2': range(3)})

In [25]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [26]:
df4

lkey  data2
0    a      0
1    b      1
2    d      2

In [30]:
pd.merge(df3,df4,on='lkey',how='outer' )

lkey  data1  data2
0    b    0.0    1.0
1    b    1.0    1.0
2    b    6.0    1.0
3    a    2.0    0.0
4    a    4.0    0.0
5    a    5.0    0.0
6    c    3.0    NaN
7    d    NaN    2.0

In [31]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],'key2': ['one', 'two', 'one'], 'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],'key2': ['one', 'one', 'one', 'two'],'rval': [4, 5, 6, 7]})
pd.merge(left,right,on='key2')

key1_x key2  lval key1_y  rval
0    foo  one     1    foo     4
1    foo  one     1    foo     5
2    foo  one     1    bar     6
3    bar  one     3    foo     4
4    bar  one     3    foo     5
5    bar  one     3    bar     6
6    foo  two     2    bar     7

### Merging On Index 

In [32]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [33]:
right1

group_val
a        3.5
b        7.0

In [37]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

### Concatenating Data 

In [42]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.concatenate([arr,arr],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
s1=pd.Series([0,1,2,56,3])
s2=pd.Series([3,4])
s3=pd.Series([6,7,4])
pd.concat([s1,s2,s3],axis=1)

0    1    2
0   0  3.0  6.0
1   1  4.0  7.0
2   2  NaN  4.0
3  56  NaN  NaN
4   3  NaN  NaN

In [72]:
pd.concat([s1,s2],axis=1,join_axes=[['a','b','c','d']])

0   1
a NaN NaN
b NaN NaN
c NaN NaN
d NaN NaN

In [74]:
print(np.arange(4)+4)

[4 5 6 7]


In [76]:
df1=pd.DataFrame(np.arange(6).reshape(2,3))
df2=pd.DataFrame(np.arange(9).reshape(3,3))

In [78]:
print(df1)
print(df2)

   0  1  2
0  0  1  2
1  3  4  5
   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8


In [86]:

df3=pd.concat([df1,df2],join='inner',keys=['level1','level2'],axis=1)

In [99]:
df3.index.names=['a']
df3.columns.names=[1,2]

In [126]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),index=['a', 'b', 'c', 'd', 'e', 'f'])

In [127]:
print(a)
print(b)

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64


In [124]:
b[-1]=np.nan

In [128]:
x=np.where(pd.isnull(a),b,a)
x

array([0. , 2.5, 2. , 3.5, 4.5, 5. ])

In [150]:
data=pd.DataFrame(np.arange(8).reshape((2,4)),
                 index=pd.Index(['Karachi','Lahore'],name='City'),
                 columns=pd.Index(['a','b','c','d'],name='Name'))

In [151]:
data

Name     a  b  c  d
City               
Karachi  0  1  2  3
Lahore   4  5  6  7

In [152]:
result=data.unstack()
result

Name  City   
a     Karachi    0
      Lahore     4
b     Karachi    1
      Lahore     5
c     Karachi    2
      Lahore     6
d     Karachi    3
      Lahore     7
dtype: int32

In [153]:
result.unstack(0)

Name     a  b  c  d
City               
Karachi  0  1  2  3
Lahore   4  5  6  7

In [154]:

result.unstack()

City  Karachi  Lahore
Name                 
a           0       4
b           1       5
c           2       6
d           3       7

In [155]:
result.unstack('City')

City  Karachi  Lahore
Name                 
a           0       4
b           1       5
c           2       6
d           3       7

In [3]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [6]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [72]:
data=pd.read_csv('pydata-book-master_ch07_macrodata.csv')
data.head()

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19

In [75]:
periods=pd.PeriodIndex(year=data.year,quarter=data.quarter,name='date')
pd.DataFrame(periods).

date
0  1959Q1
1  1959Q2
2  1959Q3
3  1959Q4
4  1960Q1

In [37]:
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')
columns

Index(['realgdp', 'infl', 'unemp'], dtype='object', name='item')

In [40]:
data=data.reindex(columns=columns)
data.head(3)

item   realgdp  infl  unemp
0     2710.349  0.00    5.8
1     2778.801  2.34    5.1
2     2775.488  2.74    5.3

In [41]:
data.index

RangeIndex(start=0, stop=203, step=1)

In [83]:
data.index=periods.to_timestamp('D','end')

In [84]:
data.head(3)

year  quarter   realgdp  realcons  realinv  \
date                                                                          
1959-03-31 23:59:59.999999999  1959.0      1.0  2710.349    1707.4  286.898   
1959-06-30 23:59:59.999999999  1959.0      2.0  2778.801    1733.7  310.859   
1959-09-30 23:59:59.999999999  1959.0      3.0  2775.488    1751.8  289.226   

                               realgovt  realdpi    cpi     m1  tbilrate  \
date                                                                       
1959-03-31 23:59:59.999999999   470.045   1886.9  28.98  139.7      2.82   
1959-06-30 23:59:59.999999999   481.301   1919.7  29.15  141.7      3.08   
1959-09-30 23:59:59.999999999   491.260   1916.4  29.35  140.5      3.82   

                               unemp      pop  infl  realint  
date                                                          
1959-03-31 23:59:59.999999999    5.8  177.146  0.00     0.00  
1959-06-30 23:59:59.999999999    5.1  177.830  2.34     0.74  
1959-09-30 23:59:59.999999999    5.3  178.657  2.74     1.09

In [85]:
ldata=data.stack().reset_index().rename(columns={0:'value'})

In [87]:
ldata[:10]

date   level_1     value
0 1959-03-31 23:59:59.999999999      year  1959.000
1 1959-03-31 23:59:59.999999999   quarter     1.000
2 1959-03-31 23:59:59.999999999   realgdp  2710.349
3 1959-03-31 23:59:59.999999999  realcons  1707.400
4 1959-03-31 23:59:59.999999999   realinv   286.898
5 1959-03-31 23:59:59.999999999  realgovt   470.045
6 1959-03-31 23:59:59.999999999   realdpi  1886.900
7 1959-03-31 23:59:59.999999999       cpi    28.980
8 1959-03-31 23:59:59.999999999        m1   139.700
9 1959-03-31 23:59:59.999999999  tbilrate     2.820

<bound method Index.drop of RangeIndex(start=0, stop=203, step=1)>